// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:760f015a-aab1-4386-89e4-d7515cabb28b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mjBOqiQL5",
    "aws_user_pools_web_client_id": "21r1g734llcak028uv6g3pcmio",
    "aws_user_files_s3_bucket": "app7693bf8496a84317a9a8d7d5c9bfdc69",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
